# Generated by Django 4.1.4 on 2022-12-17 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название фотографии')),
                ('geolocation', models.CharField(blank=True, max_length=50, verbose_name='Место выполнения фотографии')),
                ('date', models.DateField(blank=True, help_text='формат дд-мм-гггг', null=True, verbose_name='Дата фото')),
                ('names', models.CharField(blank=True, max_length=100, verbose_name='Именна людей на фотографии')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фотография')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
    ]
